### ISSUE TITLE
Cannot use it in Gingerbread?

### ISSUE THREAD

**Issue by rafaelcoutinho** [opersys/process-explorer-app#1]
I'm trying to use it in a 2.3.3 custom board but i'm getting this error when starting the server:
I/DEBUG   ( 2173): Build fingerprint: 'freescale/imx53_loco/imx53_loco:2.3.3/GRI40/eng.phi.20130726.164905:eng/test-keys'
I/DEBUG   ( 2173): pid: 2762, tid: 2762  >>> /data/data/com.opersys.processexplorer/files/node <<<
I/DEBUG   ( 2173): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
I/DEBUG   ( 2173):  r0 00000027  r1 deadbaad  r2 00000000  r3 00000000
I/DEBUG   ( 2173):  r4 00000000  r5 00000000  r6 00165acc  r7 0072f2d0
I/DEBUG   ( 2173):  r8 0057e620  r9 00000001  10 00000004  fp 7eb7f8f4
I/DEBUG   ( 2173):  ip ffffffff  sp 7eb7f8c0  lr 6fd15c79  pc 6fd15ca4  cpsr 60000030
I/DEBUG   ( 2173):  d0  6a2e7070612f7365  d1  6f72702e73797372
I/DEBUG   ( 2173):  d2  6c70786573736563  d3  6c69662f7265726f
I/DEBUG   ( 2173):  d4  0000000000000000  d5  0000000000000000
I/DEBUG   ( 2173):  d6  0000000000000000  d7  0000000000000000
I/DEBUG   ( 2173):  d8  0000000000000000  d9  0000000000000000
I/DEBUG   ( 2173):  d10 0000000000000000  d11 0000000000000000
I/DEBUG   ( 2173):  d12 0000000000000000  d13 0000000000000000
I/DEBUG   ( 2173):  d14 0000000000000000  d15 0000000000000000
I/DEBUG   ( 2173):  d16 0000000000000000  d17 0000000000000000
I/DEBUG   ( 2173):  d18 0000000000000000  d19 0000000000000000
I/DEBUG   ( 2173):  d20 0000000000000000  d21 0000000000000000
I/DEBUG   ( 2173):  d22 0000000000000000  d23 0000000000000000
I/DEBUG   ( 2173):  d24 0000000000000000  d25 0000000000000000
I/DEBUG   ( 2173):  d26 0000000000000000  d27 0000000000000000
I/DEBUG   ( 2173):  d28 0000000000000000  d29 0000000000000000
I/DEBUG   ( 2173):  d30 0000000000000000  d31 0000000000000000
I/DEBUG   ( 2173):  scr 00000000
I/DEBUG   ( 2173): 
I/DEBUG   ( 2173):          #00  pc 00015ca4  /system/lib/libc.so
I/DEBUG   ( 2173):          #01  lr 6fd15c79  /system/lib/libc.so
I/DEBUG   ( 2173): 
I/DEBUG   ( 2173): code around pc:
I/DEBUG   ( 2173): 6fd15c84 2c006824 e028d1fb b13368db c064f8df 
I/DEBUG   ( 2173): 6fd15c94 44fc2401 4000f8cc 49124798 25002027 
I/DEBUG   ( 2173): 6fd15ca4 f7f57008 2106ec7c edd8f7f6 460aa901 
I/DEBUG   ( 2173): 6fd15cb4 f04f2006 95015380 95029303 e93ef7f6 
I/DEBUG   ( 2173): 6fd15cc4 462aa905 f7f62002 f7f5e94a 2106ec68 
I/DEBUG   ( 2173): 
I/DEBUG   ( 2173): code around lr:
I/DEBUG   ( 2173): 6fd15c58 ad052204 4628680c 31fff04f e8e0f7f7 
I/DEBUG   ( 2173): 6fd15c68 6084f46f 90054629 20022200 e974f7f6 
I/DEBUG   ( 2173): 6fd15c78 447b4b1e b973681b 4623b16c 2c006824 
I/DEBUG   ( 2173): 6fd15c88 e028d1fb b13368db c064f8df 44fc2401 
I/DEBUG   ( 2173): 6fd15c98 4000f8cc 49124798 25002027 f7f57008 
I/DEBUG   ( 2173): 
I/DEBUG   ( 2173): stack:
I/DEBUG   ( 2173):     7eb7f880  700102d0  
I/DEBUG   ( 2173):     7eb7f884  70009c00  
I/DEBUG   ( 2173):     7eb7f888  0ad091cf  
I/DEBUG   ( 2173):     7eb7f88c  ffffffe0  
I/DEBUG   ( 2173):     7eb7f890  6fa00b78  /system/lib/liblog.so
I/DEBUG   ( 2173):     7eb7f894  6fa0307c  
I/DEBUG   ( 2173):     7eb7f898  70009468  
I/DEBUG   ( 2173):     7eb7f89c  700038d5  /system/bin/linker
I/DEBUG   ( 2173):     7eb7f8a0  6fb007b0  /system/lib/libm.so
I/DEBUG   ( 2173):     7eb7f8a4  6fb01630  /system/lib/libm.so
I/DEBUG   ( 2173):     7eb7f8a8  7eb7f8d4  
I/DEBUG   ( 2173):     7eb7f8ac  2aab3000  
I/DEBUG   ( 2173):     7eb7f8b0  7eb7f8d4  
I/DEBUG   ( 2173):     7eb7f8b4  00165acc  /data/data/com.opersys.processexplorer/files/node
I/DEBUG   ( 2173):     7eb7f8b8  df002777  
I/DEBUG   ( 2173):     7eb7f8bc  e3a070ad  
I/DEBUG   ( 2173): #00 7eb7f8c0  0000000f  
I/DEBUG   ( 2173):     7eb7f8c4  00000000  
I/DEBUG   ( 2173):     7eb7f8c8  00000009  
I/DEBUG   ( 2173):     7eb7f8cc  6fd249d7  /system/lib/libc.so
I/DEBUG   ( 2173):     7eb7f8d0  00000009  
I/DEBUG   ( 2173):     7eb7f8d4  fffffbdf  
I/DEBUG   ( 2173):     7eb7f8d8  0000000a  
I/DEBUG   ( 2173):     7eb7f8dc  0000000a  
I/DEBUG   ( 2173):     7eb7f8e0  0072f400  
I/DEBUG   ( 2173):     7eb7f8e4  002b4f2c  /data/data/com.opersys.processexplorer/files/node
I/DEBUG   ( 2173):     7eb7f8e8  00731adc  
I/DEBUG   ( 2173):     7eb7f8ec  ffffffff  
I/DEBUG   ( 2173):     7eb7f8f0  7eb7f964  
I/DEBUG   ( 2173):     7eb7f8f4  002b5cd8  /data/data/com.opersys.processexplorer/files/node
I/DEBUG   ( 2173):     7eb7f8f8  00000009  
I/DEBUG   ( 2173):     7eb7f8fc  ffffffff  
I/DEBUG   ( 2173):     7eb7f900  ffffffff  
I/DEBUG   ( 2173):     7eb7f904  00731a7c  
I/BootReceiver( 2333): Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
W/System.err( 2752): Starting the internal [HTTP/1.1] server on port 3001

Any ideas?

**Comment by fdgonthier** [comment]
Sadly the node binary we use, compiled from https://github.com/feichh/node, doesn't work on Gingerbread and Ice Cream Sandwich. I've tried to debug that but I can't get a clear backtrace on it. As it is now, I have _no_ idea why it crashes.

**Comment by rafaelcoutinho** [comment]
got it, it's odd cuz the rest http service does start, is that node related?

**Comment by fdgonthier** [comment]
There is a tiny HTTP/REST server which starts inside the launcher process. It allows the node process to talk to the Android runtime. Right now it's used to get the application icons but we are probably going to use it for other purposes in the future. So yeah it's totally normal that this part works.

**Comment by fdgonthier** [comment]
If it still matters to you, I have pushed a new node binary in process-explorer-web which should make the Process Explorer work on Gingerbread and Ice Cream Sandwich. Use the v0.9-dev branch. I'll push an update to the Play Store soon.
